version: "3"
services:
  app:
    cpus: 4
    mem_limit: 8g
    image: datajoint/microns_devcontainer:latest
    command: bash -c "while sleep 1000; do :; done"

  # notebook:
  #   image: microns-phase3-nda-notebook:latest
  #   build:
  #     context: .
  #   env_file: .env
  #   volumes:
  #     - ${EXTERNAL_NOTEBOOKS}:/notebooks/workspace
  #   # # Ports not compatible with network_mode: 'host',
  #   # # If changing the port is necessary you must comment out the network_mode line and uncomment the ports section.
  #   # # Then you can set the env NOTEBOOK_PORT=<some-port-number>
  #   # # Note: Without network_mode: 'host' you will be unable to access the database with env DJ_HOST=127.0.1.1 and instead
  #   # #       would need to use the network ip of the database hosting computer.
  #   # ports:
  #   #   - "${NOTEBOOK_PORT:-8888}:8888" # Jupyter notebook, defaults to port 8888 unless overridden by the NOTEBOOK_PORT env variable
  #   network_mode: 'host'
  #   # links:
  #   #   - database
  #   # ports: 
  #   #   - 8888:8888
